# app/config/security.yml
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$LT7wfsA3t9Qj31sbJO6tReDOdjB0EXZPxkMSmY38NfgswGgnmkvfq
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$moWIvLZ0UF0Y20cqx4MEVeuw8sPWwSnhMWZOyby2u15ksxWQdJY4G
                        roles: 'ROLE_ADMIN'
 
    firewalls:

        main:
            http_basic: ~
            stateless: true

            logout: true
            security: true
            anonymous: true


        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        default:
            anonymous: ~
            http_basic: ~


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/posts, roles: [ ROLE_USER, ROLE_ADMIN ] }





