# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
              memory:
                 users:
                    ryan:
                        password: $2y$12$Cjnb4dQopWseUQGvmzjRH.aTrXYUOLqJPeLxTB6N8eQWbbz75b9RS
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$Fo.L8D9kxuvkMJavgrgbfexy44gkCkI7n7Cj6M.d4I/FZUAedknMW
                        roles: 'ROLE_ADMIN'

    encoders:
              Symfony\Component\Security\Core\User\User:
                  algorithm: bcrypt
                  cost: 12

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~

        main:
            anonymous: ~
            # activate different ways to authenticate

#             http_basic: ~
#             stateless:  true

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

