site_default:
    path:     /
    defaults: { _controller: SiteBundle:Page:home }
    requirements:
    methods: GET

site_homeepage:
    path:     /home
    defaults: { _controller: SiteBundle:Page:home }
    requirements:
    methods: GET

site_about:
    path:     /about
    defaults: { _controller: SiteBundle:Page:about }
    requirements:
    methods: GET

site_contact:
    path:     /contact
    defaults: { _controller: SiteBundle:Page:contact }
    requirements:
    methods: GET

site_services:
    path:     /services
    defaults: { _controller: SiteBundle:Page:services }
    requirements:
    methods: GET







site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }

site_blog:
    path:     /index
    defaults: { _controller: SiteBundle:Posts:index }
    requirements:
    methods: GET

site_new:
    path:     /posts/new
    defaults: { _controller: SiteBundle:Posts:new }
    requirements:
    methods: GET|POST

site_show:
    path:     /show
    defaults: { _controller: SiteBundle:Posts:show }
    requirements:
    methods: GET

site_edit:
    path:     /edit
    defaults: { _controller: SiteBundle:Posts:edit }
    requirements:
    methods: GET

site_delete:
    path:     /delete
    defaults: { _controller: SiteBundle:Posts:delete }
    requirements:
    methods: GET

