site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }

site_index:
    path:     /index
    defaults: { _controller: SiteBundle:Posts:index }
    requirements:
    methods: GET

site_new:
    path:     /new
    defaults: { _controller: SiteBundle:Posts:new }
    requirements:
    methods: GET

site_show:
    path:     /show
    defaults: { _controller: SiteBundle:Posts:show }
    requirements:
    methods: GET

site_edit:
    path:     /edit
    defaults: { _controller: SiteBundle:Posts:edit }
    requirements:
    methods: GET

site_delete:
    path:     /delete
    defaults: { _controller: SiteBundle:Posts:delete }
    requirements:
    methods: GET

